language: node_js
node_js:
  - '8'
  - '10'
cache: yarn
jobs:
  include:
    - stage: checks
      name: 'Audit Packages'
      script: yarn audit
    - stage: checks
      name: 'Lint files'
      script: yarn lint
    - stage: checks
      name: 'Run tests'
      script: yarn test
    - stage: deploy
      name: 'Publish to NPM'
      script: yarn deploy

stages:
  - checks
  - name: deploy
    if: branch = master
